# Data Preprocessing Tools

## Importing the libraries


In [17]:
# for math
import numpy as np
# for charts
import matplotlib.pyplot as plt
# data mainpulation and analysis
import pandas as pd

## Importing the dataset

In [18]:
# read and create data frame
dataset = pd.read_csv('Data.csv')
# FEATURES - indepenten - info for prediction
X = dataset.iloc[:, :-1].values
# DEPENDENT VARS
y = dataset.iloc[:, -1].values

In [19]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [20]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [21]:
# sikit-learn lib with algorithms
from sklearn.impute import SimpleImputer
# create object out of class
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# make connection with object and features
imputer.fit(X[:, 1:3])
# execute
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [22]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [23]:
# Meta-estimators for building composite models with transformers
from sklearn.compose import ColumnTransformer # class
# includes scaling, centering, normalization, binarization methods.
# one hot encoder turn string of name of country to 3 column that let
# ml interact with it as number . make binary vector out of it 
from sklearn.preprocessing import OneHotEncoder # class
# make connection (first : what kind of transformation and which index , second : let other column stay)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# execute
X = np.array(ct.fit_transform(X))

In [24]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [26]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [27]:
# test set mostly for evaluate the performance of model in new observation 
from sklearn.model_selection import train_test_split #function 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [28]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [32]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [33]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [31]:
print(y_test)

[0 1]


## Feature Scaling

In [35]:
#  Scaling all vars, all features to make sure they take all values on the same scale 
#  prevent one feature dominant others which therefore will be neglected by ml model
#  feature scaling work on mean of data pool and its better to remove test set before
from sklearn.preprocessing import StandardScaler
# standardisation between -3 and 3 , normalisation between -1 and 1
# normalisation when we have normal distribution
# standardisation work all the time .
# feature scaling happen on train packages on train and test cases .
sc = StandardScaler() #rows , columns
# don't do feature scaling on dumy vars .
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
# because we dont want new scaler to fit and transform and we want to test case work
# with before scaler we only use transform , fit do calc but execs are on top of transforms
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [37]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [38]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
